### ISSUE TITLE
Golden Ratio

### ISSUE THREAD

**Issue by urmichm** [NectariosK/my-fibonacci-sequence#1]
# Constant Time 
We can use a Fibonacci Formula to calculate the N-th Fibonacci number in O(1) time.
See reference [here](https://math.hmc.edu/funfacts/fibonacci-number-formula/)

**Comment by urmichm** [comment]
I can raise a Pull Request with this approach

**Comment by NectariosK** [comment]
Great @urmichm. Please go ahead and use the Golden Ratio approach.

**Comment by urmichm** [comment]
Please review the [request](https://github.com/NectariosK/my-fibonacci-sequence/pull/2)

**Comment by urmichm** [comment]
Merged
